### ISSUE TITLE
`Text.Parsing.Parser.String.string` parser efficiency

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#105]
https://github.com/purescript-contrib/purescript-parsing/blob/e801a0ef42f3211b1602a94a269eef7ce551423f/src/Text/Parsing/Parser/String.purs#L43-L44

Does this scan all the way to the end of the input string, looking for a match, even though it already knows it failed when it doesn't find a match at index *0*? If that's what it's doing, that would be very inefficient.

**Comment by thomashoneyman** [comment]
This was fixed in #93, but we haven’t released the new version of the library yet. Good catch, though!
