### ISSUE TITLE
CodePoints uncons? Deprecate drop?

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#109]
I just noticed that `instance stringStringLike` uses `CodeUnits` for `uncons`.

https://github.com/purescript-contrib/purescript-parsing/blob/3d7976e9182d7125d4658b78629de5c92a6bbd40/src/Text/Parsing/Parser/String.purs#L27-L29

Doesn't that mean that `anyChar` will be wrong for astral characters?

https://github.com/purescript-contrib/purescript-parsing/blob/3d7976e9182d7125d4658b78629de5c92a6bbd40/src/Text/Parsing/Parser/String.purs#L54-L56

Also, the `drop` member of `StringLike` is now unused?

**Comment by drathier** [comment]
I just hit the `anyChar` issue you found above, but with the purerl backend.

**Comment by jamesdbrock** [comment]
I'm looking through the code for this package and basically the whole thing is completely oriented to UTF-16 codeunits...

**Comment by jamesdbrock** [comment]
You might try using this instead @drathier https://pursuit.purescript.org/packages/purescript-string-parsers

**Comment by drathier** [comment]
The problem is that https://pursuit.purescript.org/packages/purescript-string-parsers/6.0.1/docs/Text.Parsing.StringParser.CodePoints#v:anyChar puts the result into a `Char` so it isn't parsing code points after all. we'll be writing our own `anyCodePoint` and `anyGrapheme` later today.

**Comment by jamesdbrock** [comment]
( Reference https://pursuit.purescript.org/packages/purescript-strings/5.0.0/docs/Data.String.CodePoints#t:CodePoint )

**Comment by jamesdbrock** [comment]
Here's a parsing monad.

https://github.com/natefaubion/purescript-language-cst-parser/blob/main/src/PureScript/CST/Parser/Monad.purs

**Comment by jamesdbrock** [comment]
CPS-style purescript parsing monad WIP

https://github.com/cdepillabout/cabal2nixWithoutIFD/blob/fafc453e3ad4f9690add474a070aa734d4051fcd/purescript-parser-combinator/src/Parser.purs

Adapted from 

https://github.com/jonascarpay/alloy/blob/master/src/Parser/Parsec.hs

Adapted from Parsec.

**Comment by jamesdbrock** [comment]
@drathier I'd like to see your `anyGrapheme` parser. Link please? Do you think that this library should include `anyGrapheme`?

**Comment by jamesdbrock** [comment]
@drathier Would PR #119  solve your problem? That PR deletes the `StringLike` class. Would you like to rely on that class for purerl? Or have your implemented the `Data.String` API for purerl?

**Comment by jamesdbrock** [comment]
More from @drathier :
https://discourse.purescript.org/t/make-char-represent-an-opaque-code-point-instead-of-utf-16-code-unit/2630
