### ISSUE TITLE
lazy errors

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#128]
We should probably change all error messages to be lazy like this with `defer`.

> I chose to make error messages deferred to avoid the cost of generating the error messages until they're needed. Feels like a small thing, but the waste just bothers me too much.
> 
>
> _Originally posted by @fsoikin in https://github.com/purescript-contrib/purescript-parsing/pull/127#r778983836_

**Comment by fsoikin** [comment]
It turns out that making _all_ errors lazy is pointless, because most of them are actually constant strings. 

Still, a facility for doing that would be useful, I think. So I added a facility and made use of it in those places where the error messages are not trivial.
