### ISSUE TITLE
Delete the module prefix Text

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#147]
The next time we feel like breaking everything.

**Comment by jamesdbrock** [comment]
I think I’ll delete ~~`Text.Parsing.Parser`~~ prefix and replace with `Parsing`. @thomashoneyman

**Comment by thomashoneyman** [comment]
👍

**Comment by JordanMartinez** [comment]
@jamesdbrock I think we should do this in the `0.15.0` release
