### ISSUE TITLE
Combinator variations

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#177]
We need to figure out which combinators to keep and which are redundant after the CPS refactor #154

**Comment by jamesdbrock** [comment]
Here is what the benchmarks from https://github.com/purescript-contrib/purescript-parsing/pull/176#issuecomment-1086773579 show.

* `List.manyRec` is faster than `List.many`. Let's export a `Combinators.many = List.manyRec`.
* `sepByRec` is faster than `sepBy`. `sepBy` is not stack-safe. Let's replace `sepBy` with `sepByRec`.
* `chainlRec` is faster than `chainl`. `chainl` is not stack-safe. Let's replace `chainl` with `chainlRec`.
* `chainr` is faster than `chainrRec`. `chainr` is not stack-safe. Not clear what to do here.
* `manyTillRec` is faster than `manyTill`. `manyTill` is not stack-safe. Let's replace `manyTill` with `manyTillRec`.

**Comment by jamesdbrock** [comment]
Also, why are some of the combinators still blowing the stack?

**Comment by natefaubion** [comment]
Ideally the non Rec versions should still be stack safe. I don’t think we should replace them without understanding why they low the stack.

**Comment by jamesdbrock** [comment]
Ok.

**Comment by natefaubion** [comment]
I can't replicate the stack issues with `sepBy`. When I run this program:

```purescript
module Main where

import Prelude

import Data.Array as Array
import Data.List (List)
import Data.String (joinWith)
import Effect (Effect)
import Effect.Class.Console (logShow)
import Parsing (Parser, runParser)
import Parsing.Combinators (sepBy)
import Parsing.String (string)

testString :: String
testString = joinWith " " $ Array.replicate 100000 ("A")

testParser :: Parser String (List String)
testParser = sepBy (string "A") (string " ")

main :: Effect Unit
main = do
  let res = runParser testString testParser
  logShow res
```

I get the full result printed.

**Comment by natefaubion** [comment]
Oh, interesting! I think it's because the parser actually fails to parse. You have "23" repeated, and are using sepBy, which will result in a parse error. Your original example is blowing the stack in the `throw` branch of `alt`. We need to bounce the `throw` continuation.

**Comment by jamesdbrock** [comment]
@natefaubion fixed the stack safety of `alt` and `bind` in #178

**Comment by jamesdbrock** [comment]
I fixed the parse errors that you noticed, here are the new benchmarks: https://github.com/purescript-contrib/purescript-parsing/pull/179#issuecomment-1088212080

* `List.manyRec` is faster than `List.many`. Let's export a `Combinators.many = List.manyRec`.
* `sepByRec` and `sepBy` appear to be about the same speed. Let's delete `sepByRec`?
* `chainlRec` is faster than `chainl`. Let's replace `chainl` with `chainlRec`?
* `chainr` is faster than `chainrRec`. Let's delete `chainrRec`?
* `manyTillRec` is faster than `manyTill`. Let's replace `manyTill` with `manyTillRec`?

Or maybe we should try to do #155 first before we make these decisions.

**Comment by jamesdbrock** [comment]
I fixed the parse errors that you noticed, here are the new benchmarks: https://github.com/purescript-contrib/purescript-parsing/pull/180#issuecomment-1088505940

* `List.manyRec` is faster than `List.many`. Let's export a `Combinators.many = List.manyRec`.
* `sepByRec` is faster then `sepBy`. Let's replace `sepBy` with `sepByRec`?
* `chainlRec` is faster than `chainl`. Let's replace `chainl` with `chainlRec`?
* `chainr` is faster than `chainrRec`. Let's delete `chainrRec`?
* `manyTillRec` is faster than `manyTill`. Let's replace `manyTill` with `manyTillRec`?

Or maybe we should try to do #155 first before we make these decisions.

**Comment by jamesdbrock** [comment]
I think what I'm seeing here https://github.com/purescript-contrib/purescript-parsing/pull/181#issuecomment-1089823204
is that 

* The way to write the combinators so that they will run fastest is by writing the combinators in terms of `tailRecM`, which is how `sepEndBy1Rec` is written.
* The second fastest way is to write them in terms of `List.manyRec`, which is how `sepByRec` is written. (`List.manyRec` is written in terms of `tailRecM`).
* It's possible that we could squeeze even more speed out by writing these combinators CPS-style as I think @natefaubion suggested in #155 ? But if we did that then we would still be using `tailRecM`, I think?

**Comment by jamesdbrock** [comment]
I still don't understand why `chairr` is faster than `chainrRec` https://github.com/purescript-contrib/purescript-parsing/pull/181#issuecomment-1089823204

**Comment by natefaubion** [comment]
https://github.com/purescript-contrib/purescript-parsing/blob/3b2f7a0b14f68a63b0be97d6e78d08714d3da530/src/Parsing/Combinators.purs#L436

`chainrRec` is probably slower because the foldl is being strictly computed on every iteration. It needs to be `defer`ed, or guarded in some way.
