### ISSUE TITLE
Fully remove the `Parsing.Pos` module?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-parsing#190]
Since the `Parsing.Pos` module is being deprecated and all of its members are already being re-exported by the `Parsing` module, can we just remove it entirely? The `Text.Parsing....` module rename change is already a breaking change that forces users to update their imports. We may as well make this breaking change so there's one less breaking change in the `0.16.0` round of changes.

Thoughts?

**Comment by jamesdbrock** [comment]
I agree, I'll do that.
