### ISSUE TITLE
Export `digit`

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/purescript-parsing#24]
It's referred to in the documentation, but as far as I can tell, it is only actually defined in `Main` (and therefore can't be imported by users of this library).

Could it go in `Text.Parsing.Parsers.String`?

**Comment by garyb** [comment]
Makes sense to me :+1:

**Comment by paf31** [comment]
:+1: Sounds good.

**Comment by LiamGoodacre** [comment]
This has been done: [`Text.Parsing.Parser.Token#digit`](https://pursuit.purescript.org/packages/purescript-parsing/0.8.0/docs/Text.Parsing.Parser.Token#v:digit)
Close?

**Comment by hdgarrood** [comment]
Thanks :)
