### ISSUE TITLE
Add `eof` for Token parsers?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/purescript-parsing#25]
Something like this:

``` purescript
eof :: forall a. Parser (List a) Unit
eof =
  get >>= \(input :: List a) ->
    unless (null input) (fail "expected eof")
```

I guess it would go into `Text.Parsing.Parser.Token?

By the way, is it right that we need that type annotation on `input`? Without it, type unification fails.

**Comment by paf31** [comment]
:+1: 

Does unification fail, or does type class lookup fail?

**Comment by hdgarrood** [comment]
Oh sorry, yes, type class lookup fails. The error was:

```
  No type class instance was found for

    Control.Monad.State.Class.MonadState (List _72)
                                         (ParserT (List a65) Identity)
```

**Comment by garyb** [comment]
I think that's "right" - missing fundeps means the `a` is unknown for this usage.

**Comment by hdgarrood** [comment]
Ah, right! I think I understand why fundeps are useful now.

**Comment by felixSchl** [comment]
I'd welcome such a parser, but could the concrete list type not be replaced by a typeclass and the whole thing be `ParserT` instead of `Parser`?

**Comment by hdgarrood** [comment]
ParserT, yes. I'm not sure if a good type class for asking whether something is empty can exist, though. List is probably the right type to use for a token stream anyway because you only want to take items off the left end one at a time too; it's probably better for performance to restrict to List and make people convert, than to let people use eg Array, which could make otherwise linear time parsers accidentally quadratic, I think.
