### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by adarqui** [purescript-contrib/purescript-parsing#34]
Hi,

I was wondering if anyone has an idea why large strings causes stack limit exceptions. While working on my bbcode parser which uses purescript-parsing, I ran into the issue that big forum posts cause exceptions. The strings in these forum posts are not continuous, such as in these tests I wrote. So it could be an entirely different issue in those specific cases. However, here is some code that causes stack limit exceptions via large strings:

https://github.com/adarqui/cardiac-arrest/blob/master/experiments/parsing/big-strings/purescript/purescript-parsing

more specifically:
https://github.com/adarqui/cardiac-arrest/blob/master/experiments/parsing/big-strings/purescript/purescript-parsing/test/Main.purs

Here is the example output from those tests:
```
* Running tests...
→ Suite: test big strings
  → Testing string of size: 1024
→ Testing string of size: 2048
→ Testing string of size: 3072
☠ Failed: simple strings because Maximum call stack size exceeded
→ Testing string of size: 1024
→ Testing string of size: 2048
→ Testing string of size: 3072

1 test failed:

In "test big strings":
  In "simple strings":
    Maximum call stack size exceeded

→ Testing string of size: 1024
→ Testing string of size: 2048
→ Testing string of size: 3072
```

So somewhere around ~3072 bytes, purescript-parsing throws a stack limit exception.

Thanks!

**Comment by paf31** [comment]
One option is to use `ParserT` to transform the `Trampoline` monad from `purescript-free`. That should cause monadic binds to be trampolined, but it will cause some slowdown.

**Comment by adarqui** [comment]
@paf31,

cool thanks! I will try to figure that out.

Also, FWIW, purescript-string-parsers doesn't exception. Is that to be expected: purescript-parsing causing an exception with my tests, but purescript-string-parsers working just fine?

Here's the equivalent purescript-string-parsers code which passes, just for reference:

https://github.com/adarqui/cardiac-arrest/blob/master/experiments/parsing/big-strings/purescript/purescript-string-parsers/test/Main.purs

Thanks alot

**Comment by adarqui** [comment]
Hi @paf31,

Thanks for the advice about using a Trampoline. Here is some test code which passes my big string tests:

https://github.com/adarqui/cardiac-arrest/tree/master/experiments/parsing/big-strings/purescript/purescript-parsing-using-trampolines

For future reference ^^ The code is considerably slower as you stated, but it doesn't stack exception so, nice!

I'm going to put that trampoline code into it's own library in case anyone else needs it.

Thanks!
