### ISSUE TITLE
Reconsider alternative instance for Transformer typeclasses

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-parsing#56]
When I first used `MonadState` instance for ParserT I had `ParserT s (State s') a` and I was expecting it to be defined as in most of transformers:

``` hs
(MonadState s m) => MonadState s (ParserT s' m)
```
but instead it's defined as:

``` hs
(Monad m) => MonadState (ParseState s) (ParserT s m)
-- `MonadThrow` and `MonadError` are defined in same fashion.
```

So my question is, why it's like that? I think If we had normal definitions of `Monad*` then `ParseT` would be more useful in transformer stacks (we could expose functions from this typeclasses with different name, for users to still be able to manipulate `ParserT`'s Internal structure).

**Comment by paf31** [comment]
Yes, we should probably break this, those instances would be more useful.
