### ISSUE TITLE
Use free-ish representation instead of StateT and friends

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-parsing#59]
Resently I came across  the paper ["Parallel parsing processes"](http://www.cse.chalmers.se/edu/year/2015/course/afp/Papers/parser-claessen.pdf). It's sort of encoding Parser using FreeAlternative like structure, so t could be adopted and should give performance and some other benefits I think.

**Comment by paf31** [comment]
Can you please summarize how this would improve performance? My guess would be that the overhead would cost quite a bit.

**Comment by safareli** [comment]
Main difference would be that choice is breadth first instead of depth first. and we wouldn't need `try` I think. but first to get same functionality what we have now, we would need to implement FreeMonadPlusT

**Comment by paf31** [comment]
This sounds very different to what this library offers. I suggest starting by implementing it in a separate library.
