### ISSUE TITLE
combine purescript-string-parsers ans purescript-parsing

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-parsing#69]
Not totally sure, but I think we can somehow generalize current encoding of parser such that the parser from ps-string-parsers will be an instance of it.

What I see in ps-string-parsers is that it uses different Position type which is basically a cursor in the input state. but what if we want to have same performance benefits (of not allocating new states) when we have some tokens as array, or as some structure, where moving "cursor" (position) is cheap. 

We can do similar thing as `Stream` here to make that possible but maybe we can combine cursor based Streams and non cursor bases streams and have one parser lib.

related #62 #58

**Comment by jamesdbrock** [comment]
We should do this, or something like it.

**Comment by jamesdbrock** [comment]
This is something that we're still thinking about but most of the circumstances described in the issue description have changed.

* __string-parsers__ uses slices now instead of index.
* __parsing__ is fast now.
