### ISSUE TITLE
Text.Parsing.Parser.ArrayBuffer

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/purescript-parsing#88]
I want to parse the raw `Uint8` bytes of a [Javascript ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer). You know, like the [`ByteString` instance for Megaparsec Streams](https://hackage.haskell.org/package/megaparsec-8.0.0/docs/Text-Megaparsec-Stream.html#t:Stream), or [Data.Attoparsec.ByteString](http://hackage.haskell.org/package/attoparsec/docs/Data-Attoparsec-ByteString.html). 

Is there a good way to do this in Purescript? I can't find it. If this doesn't exist, maybe we could add a new module to __purescript-parsing__ called `Text.Parsing.Parser.ArrayBuffer`? It seems like __purescript-parsing__ was designed to be extended in this way.

This module would be a peer of `Text.Parsing.Parser.String` and `Text.Parsing.Parser.Token`, and similarly constructed.

Or maybe this would be better as a separate library, since it would add some new dependencies:

https://pursuit.purescript.org/packages/purescript-arraybuffer
https://pursuit.purescript.org/packages/purescript-arraybuffer-types

Thoughts?

**Comment by jamesdbrock** [comment]
The fact that [`getUint8`](https://pursuit.purescript.org/packages/purescript-arraybuffer/10.0.2/docs/Data.ArrayBuffer.DataView#v:getUint8) is an `Effect` function might complicate this.

**Comment by garyb** [comment]
I don't think the `Effect` is a problem, you can use the `m` part of `ParserT` to handle that. Something along the lines of:

``` purescript
import Control.Monad.State (get, modify_)
import Control.Monad.Trans.Class (lift)
import Data.ArrayBuffer.DataView (getUint8)
import Data.ArrayBuffer.Types (DataView)
import Data.Maybe (Maybe(..))
import Data.UInt (UInt)
import Effect.Class (class MonadEffect, liftEffect)
import Text.Parsing.Parser (ParseState(..), ParserT, fail)
import Text.Parsing.Parser.Pos (Position(..))

uint8 ∷ ∀ m. MonadEffect m ⇒ ParserT DataView m UInt
uint8 = do
  ParseState input (Position { column }) _ <- get
  lift (liftEffect (getUint8 input column)) >>= case _ of
    Nothing → fail "Unexpected EOF"
    Just i → do
      modify_ \(ParseState _ position _) ->
        ParseState input (Position { line: 0, column }) true
      pure i
```

I haven't tested that, so it might not behave quite right, but it compiles and shouldn't be too far off.

The `Position` hard coded into `ParserT` isn't really ideal for this purpose 😕, hence the fixed `line: 0`.

**Comment by jamesdbrock** [comment]
Good idea. I'll take a shot at a PR for this.

**Comment by jamesdbrock** [comment]
https://pursuit.purescript.org/packages/purescript-arraybuffer is not a __purescript-contrib__ library, is it okay for __purescript-parsing__ to depend on it?

**Comment by jamesdbrock** [comment]
__purescript-arraybuffer__ is really nice because it handles endianness.

**Comment by garyb** [comment]
Hmm, good point - we try to avoid extra-contrib dependencies unless the library is maintaned by one of us in contrib/core (in the past we've had dependencies that end up blocking libraries that need updates).

Maybe this would be better off as a new library that depends on `-arraybuffer` and `-parsing`. I'd be happy to add a link to it in the readme here to help others find it, if you put something together.

**Comment by jamesdbrock** [comment]
Also transitively depends on non-contrib library https://pursuit.purescript.org/packages/purescript-typelevel
